### ISSUE TITLE
如何私信你啊

### ISSUE THREAD

**Issue by AGhuawei** [Anonymous-ghost/AttackWebFrameworkTools-5.0#18]
膜拜大佬，特意注册的github来问，这软件要什么条件才能使用，我在学校报名CTF的特别喜欢这行业，希望你能私信发个下载地址也想加你个联系方式，谢谢你为安全行业做出巨大的贡献

**Comment by Anonymous-ghost** [comment]
软件在release已经发布。另外此软件是渗透测试软件属于漏洞利用型软件可能不适合ctf使用。如果想测试软件建议本地搭建漏洞环境。或者在线靶场环境。切勿对未授权的互联网网站进行渗透测试。

**Comment by AGhuawei** [comment]
谢谢，我这就联系你

**Comment by Anonymous-ghost** [comment]
你从哪里知道这个软件的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月21日(周四) 下午4:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Anonymous-ghost/AttackWebFrameworkTools-5.0] 如何私信你啊 (Issue #18)




 
谢谢，我这就联系你
