### ISSUE TITLE
最新版本运行报错

### ISSUE THREAD

**Issue by dbgee** [Anonymous-ghost/AttackWebFrameworkTools-5.0#19]
刚开始运行正常，过一段时间就会报错
![image](https://user-images.githubusercontent.com/46910972/186868690-61a146c5-26d6-4fae-ba09-f86a2ccb9638.png)
然后回到软件目录一看，好多dll 被自动删除了【没有装杀软】

![image](https://user-images.githubusercontent.com/46910972/186868839-58322b38-b467-4cff-98bc-12caffa5260c.png)

**Comment by Anonymous-ghost** [comment]
你的核心dll没有了能不报错吗httpsend.dll 核心库。删除dll原因是因为你网络问题或者是dll加载出错导致。注意看帮助视频。别一上来就用

**Comment by dbgee** [comment]
程序自己删除的

**Comment by dbgee** [comment]
我当然知道为啥报错，但是为啥删除，什么情况下删除？

**Comment by Anonymous-ghost** [comment]
网络不稳定会删除程序。如果出现删除问题你网络有问题。连接不到更新服务器
