### ISSUE TITLE
如何启动-无反应

### ISSUE THREAD

**Issue by yangyang1144** [Anonymous-ghost/AttackWebFrameworkTools-5.0#20]
我启动软件的姿势是不是不太对 为何没有任何反应
![image](https://user-images.githubusercontent.com/83336628/188308374-777af115-6120-437d-bb16-b8dec9f1ade7.png)
![image](https://user-images.githubusercontent.com/83336628/188308396-8faa5b2f-ce4d-45fb-85fc-4645a7b97576.png)

**Comment by Anonymous-ghost** [comment]
你姿势不对。关闭你本地代理
